### ISSUE TITLE
Vertical Usage and Node Level Limitation

### ISSUE THREAD

**Issue by caginbektas** [bumbeishvili/d3-organization-chart#7]
Hello David,

First of all, that an amazing job! Thanks for sharing that all free, I am glad!

Is that possible to use the chart vertically and limit the initial number of level of the nodes. 
As default, it comes horizontal and with 3 levels of nodes.

Thanks in advance!

**Comment by bumbeishvili** [comment]
Hi @caginbektas  again, and thanks

Regarding your questions:

> Is that possible to use the chart vertically, it comes horizontal

No, currently there is not an option to convert chart from vertical to horizontal  or vice versa 


> Is that possible to limit the initial number of level of the nodes.

Yes, it's possible, you just need to correctly set an expanded flag to nodes. 

so, if the node has `{expanded: true}` set, it will be expanded, otherwise, it will be collapsed (unless it's children or neighbours don't have the similar flag set to true )


Take a look at data generation wiki - https://github.com/bumbeishvili/d3-organization-chart/wiki/Data-Generation, and pay attention to last piece of code 

` expanded:expanded          // If we want node to be expanded`

**Comment by caginbektas** [comment]
Thank you so much!
